### ISSUE TITLE
ValueError when importing?

### ISSUE THREAD

**Issue by circles-png** [Wiper-R/discord-ext-games#2]
`ValueError: 'blank' in __slots__ conflicts with class variable`

Full traceback:

```
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from discord.ext.games import TicTacToe
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/games/__init__.py", line 1, in <module>
    from .tic_tac_toe import TicTacToe
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/games/tic_tac_toe/__init__.py", line 1, in <module>
    from .core import TicTacToe
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/games/tic_tac_toe/core.py", line 6, in <module>
    from .config import CONFIG
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/games/tic_tac_toe/config.py", line 1, in <module>
    class CONFIG:
ValueError: 'blank' in __slots__ conflicts with class variable
```

Using repl.it to run bot

**Comment by shivangrathore** [comment]
Eventually the issue was fixed but the package is not updated on pypi. You can just install from github for now.

**Comment by shivangrathore** [comment]
I Updated it on pypi.
