### ISSUE TITLE
TypeError: sequence item 2: expected str instance, Emoji found

### ISSUE THREAD

**Issue by Joseph-Joestar-hamon** [Wiper-R/discord-ext-games#3]
`Traceback (most recent call last):
  File "D:\Python\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "D:\Python\lib\site-packages\discord\ext\games\tic_tac_toe\core.py", line 112, in runner
    await self.run_move(self._turn_of, emoji)
  File "D:\Python\lib\site-packages\discord\ext\games\tic_tac_toe\core.py", line 144, in run_move
    embed = self.board_to_embed()
  File "D:\Python\lib\site-packages\discord\ext\games\tic_tac_toe\core.py", line 88, in board_to_embed
    "\n".join(
  File "D:\Python\lib\site-packages\discord\ext\games\tic_tac_toe\core.py", line 89, in <genexpr>
    "\u200b".join(board[i] for i in range(j, j + 3)) for j in range(0, 9, 3)
TypeError: sequence item 2: expected str instance, Emoji found`

**Comment by shivangrathore** [comment]
Did you fixed it?
